version: "3.8"

services:
  moodle:
    image: bitnami/moodle:latest
    ports:
      - 80:8080
      - 443:8443
    # environment:
    # - MOODLE_SSLPROXY=false
    #   - MOODLE_HOST="0.0.0.0"
    # - MOODLE_REVERSEPROXY=true
    env_file:
      - .env
    networks:
      - reto-4
    depends_on:
      - db
    # volumes:
    #   - ./moodle_data:/bitnami/moodle

  db:
    build:
      context: .
    command: ./cloud_sql_proxy -credential_file /service-account.json -instances=reto-4-384523:us-central1:postgres=tcp:0.0.0.0:5432
    expose:
      - 5432
    volumes:
      - ./service-account.json:/service-account.json
    networks:
      - reto-4

networks:
  reto-4:
# volumes:
#   moodle_data:
