version: "3.3"

services:
  moodle:
    image: bitnami/moodle:4.1.2
    ports:
      - 80:8080
      - 443:8443
    environment:
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=34.30.27.152
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodledb
      - MOODLE_DATABASE_USER=moodleuser
      - MOODLE_DATABASE_PASSWORD=password
      - MOODLE_SKIP_BOOTSTRAP=no
      - MOODLE_USERNAME=user
      - MOODLE_PASSWORD=secret
    # volumes:
    #   - /nfs-moodle:/bitnami
